name: test_build
on: workflow_dispatch
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install esphome
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install esphome
      - name: Build ESP32
        run: esphome compile ci/sample-esp32.yaml
