name: test_build
on: workflow_dispatch
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: pip3 install esphome
      - run: esphome version
